[package]
name = "plane_ticket"
version = "0.1.0"
authors = ["Spike <joritomartins@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# rand = "0.5.5"

# chrono = "0.4"
# lazy_static = "1.4.0"
